import  pandas as pd
df = pd.read_csv("employees.csv")
print(df)
print(df.head())
print(df.describe())
print(df.info)
print(df.columns)
print(df.isna().sum())
cleaned = df.dropna()
print(cleaned)
print(len(cleaned))
print(pd.isna(df["Gender"]))
print(df["Salary"].sum())
df = df.drop("Last Login Time", axis='columns')
print(df)
on = pd.get_dummies(df , columns=['Gender'])
print(on)